-- 阶段 1：为业务表增加 tenant_id（默认 1 = 历史单租户数据）。
-- 使用普通 ADD COLUMN（兼容 MySQL 8.0 任意小版本）；重复部署时「列已存在」会报错，由 docker-entrypoint 中 mysql --force 忽略并继续。
-- 索引与唯一约束见 schema_tenant_id_phase1_constraints.sql

ALTER TABLE aa_commit ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE aa_commit_diff ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE aa_webhook_delivery ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE aa_system_config ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' FIRST;

ALTER TABLE biz_user ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_project ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_project_member ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_project_table ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_option_group ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_table_column ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_record ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_record_field ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_record_comment ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_attachment ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_record_history ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;

ALTER TABLE biz_quote_project ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_quote_module ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_quote_item ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_quote_baseline ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_quote_risk_config ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_quote_price_config ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_quote_result ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_quote_document ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_quote_contract_draft ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_quote_actual ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE biz_quote_preset_item ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;

ALTER TABLE aa_ai_analysis_config ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE aa_ai_analysis_job ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE aa_ai_analysis_result ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE aa_ai_token_usage ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
ALTER TABLE aa_project_daily_summary ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID' AFTER id;
